### ISSUE TITLE
Fix `first/last_published_at` bug on page aliases in Wagtail

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#8375]
~~We introduced `network-api/networkapi/management/commands/fix_alias_page_first_last_published.py` to fix an issue with data that was introduced prior to Wagtail v2.16, and ran this against the production database. This was a one-time operation, and we can safely remove this management command again.~~

***

**UPDATE 2022-03-24**

_Changing the scope of this ticket to reflect the discussion below._

Create a fix for https://github.com/wagtail/wagtail/issues/8080.

The issue is that the `first_published_at` and `last_published_at` fields of a page alias are `None` when a new page is first saved as draft and then published.

**Comment by TheoChevalier** [comment]
Hmmm, let’s keep it around a bit longer… I just noticed the issue is still happening with new pages:

Alias pages created after the 2.16 migration, **and** after I ran the `fix_alias_page_first_last_published` command, keep showing `Not published yet`:

- https://foundation.mozilla.org/fr/blog/vero-supporting-creatives-at-mozfest/
- https://foundation.mozilla.org/fr/blog/seven-new-senior-fellows-selected-to-help-fuel-the-movement-for-trustworthy-ai/
- https://foundation.mozilla.org/fr/blog/common-voice-announces-400000-in-awards-for-kiswahili-voice-technologies/
- https://foundation.mozilla.org/fr/blog/social-moments-at-mozfest-virtual-2022/


I created a new page on staging (where I did run the command right before running it on prod), and I was *not* able to reproduce:

https://foundation.mofostaging.net/fr/blog/test/

I’m now wondering if this has something to do with the editor’s permission

**Comment by TheoChevalier** [comment]
Ok, managed to reproduce the issue, it’s unrelated to permission: it works when you **directly hit publish** when creating the page, but it doesn’t work when you first save a draft, **then** publish this draft.

I filed https://github.com/wagtail/wagtail/issues/8080

Moving the issue to blocked until we get a Wagtail fix released & deployed

**Comment by tbrlpld** [comment]
It looks like the issue @TheoChevalier has submitted to Wagtail is not yet resolved. What I my task here? Should this be pushed back until the fix is in Wagtail? Or would it be for me to submit the fix to Wagtail? 


cc @bheasman @Pomax

**Comment by tbrlpld** [comment]
@Pomax so this ticket is just to track the progress on the Wagtail issue? Sorry, I am confused about what action we are taking here 😅
